version: 0.2
phases:
  pre-buld:
    commands:
    - echo "Entered the prebuild phase"
  build:
    commands:
    - echo "Enter build phase"
    - mvn clean prepare-package war:explode
  post-build:
    commands:
    -echo "enter the post build phase"
    -mv target/deploy ./
artifacts:
  files:
    -deploy/**/*